export const USERS = [
	{
        id: 1,
        first_name: "John",
        last_name: "Popescu",
        phone_number: "0712345678",
        email: "ion.popescu@example.com",
        description: "win + sters tot",
        reparation_status: "Reparat",
        reparation_price: 200,
        date: "2024-08-20",
    },
    {
      id: 2,
      first_name: "Ion",
      last_name: "Popescu",
      phone_number: "0712345678",
      email: "ion.popescu@example.com",
      description: "win + curatare de praf si pasta + inlocuire ecran",
      reparation_status: "Preluat",
      reparation_price: 100,
      date: "2024-08-22",
  },
  {
    id: 3,
    first_name: "Titi",
    last_name: "Popescu",
    phone_number: "0712345678",
    email: "ion.popescu@example.com",
    description: "win + curatare de praf si pasta + inlocuire ecran",
    reparation_status: "In curs de reparatie",
    reparation_price: 300,
    date: "2024-08-21",
  },
];